pipeline {
	agent none
	stages {
stage('backend'){
	agent {
	docker { image 'node:20-alpine' }
	}
steps {
sh 'node --version'
}
}
stage('frontend'){
agent {
docker { image 'node:16-alpine' }
}
steps{
sh 'node --version'

}}}}
